quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=PasswordBaru123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/expert_system
quarkus.hibernate-orm.database.default-schema=security_assessment

# batas ukuran file upload (samakan dengan MAX_FILE_SIZE_BYTES di FileValidationService)
quarkus.http.limits.max-body-size=5M

# Swagger UI: tampilkan juga di mode produksi (default hanya di dev)
quarkus.swagger-ui.always-include=true
# path Swagger UI (default: /q/swagger-ui)
quarkus.swagger-ui.path=/swagger-ui

# JWT: verifikasi token (public key) + penerbitan token (private key)
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://expertsystem.akbar.rizki
smallrye.jwt.sign.key.location=privateKey.pem
# lama berlaku token (detik) - 8 jam
jwt.duration.seconds=28800